### ISSUE TITLE
NavAPI.launch is not a function

### ISSUE THREAD

**Issue by jonatantroedsson** [gcazaciuc/storysnap#1]
Heya!

Willing to try this out, but can get neither the examples nor my own tests to work, always returning the same error:

```
bin/storysnap --script ./../examples/programatic-usage.js --test --screenshotDir ./screenshots --reporters xunit,progress --threshold 0.1
Starting Storysnap....
Started Storysnap....
TypeError: NavAPI.launch is not a function
    at module.exports (/Users/Jonatan/Documents/LF/storysnap/examples/programatic-usage.js:4:46)
    at Timeout.setTimeout [as _onTimeout] (/Users/Jonatan/Documents/LF/storysnap/bin/storysnap:47:9)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
/Users/Jonatan/Documents/LF/storysnap/src/chrome-launcher.js:32
    return launcher.kill();
                   ^

TypeError: Cannot read property 'kill' of null
    at Object.kill (/Users/Jonatan/Documents/LF/storysnap/src/chrome-launcher.js:32:20)
    at Object.kill (/Users/Jonatan/Documents/LF/storysnap/src/navigation-api.js:62:25)
    at process.handleExit (/Users/Jonatan/Documents/LF/storysnap/bin/storysnap:76:10)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:329:26)
```

Any help?

**Comment by gcazaciuc** [comment]
Hi,

Please provide the following info:
1. Chrome version(make sure you have at least Chrome 59 installed - currently beta)
2. OS( Windows support for headless Chrome should be on in the following weeks).

Thanks for providing feedback.

**Comment by jonatantroedsson** [comment]
Hi!

Chrome Version 59.0.3071.86
OS: OS X El capitan 10.11.6

Running lighthouse chrome launcher independently works, launching up Chrome Canary.

**Comment by gcazaciuc** [comment]
Version 2.0 has been completely overhauled. Storysnap now handlers only screenshoting of Storybook. Navigation is left out to Puppeteer.
